// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_gamesystem.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cs_gamesystem.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SProtoSpace {

namespace {

const ::google::protobuf::EnumDescriptor* EGameSystem_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ESystemModule_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ELevelMode_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ESystemConditionType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ETowerFloorType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* EFloorLevelType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_cs_5fgamesystem_2eproto() {
  protobuf_AddDesc_cs_5fgamesystem_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cs_gamesystem.proto");
  GOOGLE_CHECK(file != NULL);
  EGameSystem_descriptor_ = file->enum_type(0);
  ESystemModule_descriptor_ = file->enum_type(1);
  ELevelMode_descriptor_ = file->enum_type(2);
  ESystemConditionType_descriptor_ = file->enum_type(3);
  ETowerFloorType_descriptor_ = file->enum_type(4);
  EFloorLevelType_descriptor_ = file->enum_type(5);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cs_5fgamesystem_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_cs_5fgamesystem_2eproto() {
}

void protobuf_AddDesc_cs_5fgamesystem_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023cs_gamesystem.proto\022\013SProtoSpace*\335\002\n\013E"
    "GameSystem\022\024\n\020GAME_SYSTEM_BASE\020\001\022\024\n\020GAME"
    "_SYSTEM_ITEM\020\002\022\026\n\022GAME_SYSTEM_PLAYER\020\003\022\024"
    "\n\020GAME_SYSTEM_HERO\020\004\022\024\n\020GAME_SYSTEM_SOUL"
    "\020\005\022\025\n\021GAME_SYSTEM_QUEST\020\006\022\025\n\021GAME_SYSTEM"
    "_LEVEL\020\007\022\025\n\021GAME_SYSTEM_ROYAL\020\010\022\024\n\020GAME_"
    "SYSTEM_SHOW\020\t\022\026\n\022GAME_SYSTEM_FRIEND\020\n\022\024\n"
    "\020GAME_SYSTEM_SHOP\020\013\022\025\n\021GAME_SYSTEM_TOWER"
    "\020\014\022\024\n\020GAME_SYSTEM_CHAT\020\r\022\023\n\017GAME_SYSTEM_"
    "ADV\020\016\022\023\n\017GAME_SYSTEM_MAX\020\?*\342\001\n\rESystemMo"
    "dule\022\026\n\022ESYSTEMMODULE_NONE\020\000\022\027\n\023ESYSTEMM"
    "ODULE_TOWER\020\001\022\033\n\027ESYSTEMMODULE_DAILYTASK"
    "\020\002\022\034\n\030ESYSTEMMODULE_BRANCHTASK\020\003\022\033\n\027ESYS"
    "TEMMODULE_DIFFLEVEL\020\004\022\026\n\022ESYSTEMMODULE_M"
    "AIL\020\005\022\025\n\021ESYSTEMMODULE_PET\020\006\022\031\n\025ESYSTEMM"
    "ODULE_OFFICAL\020\007*<\n\nELevelMode\022\023\n\017ELEVELM"
    "ODE_EASY\020\001\022\031\n\025ELEVELMODE_DIFFICULTY\020\002*\255\001"
    "\n\024ESystemConditionType\022\031\n\025SYSTEM_CONDITI"
    "ON_NONE\020\000\022\032\n\026SYSTEM_CONDITION_LEVEL\020\001\022\034\n"
    "\030SYSTEM_CONDITION_TASK_ID\020\002\022\035\n\031SYSTEM_CO"
    "NDITION_STAGE_ID\020\003\022!\n\035SYSTEM_CONDITION_O"
    "FFICE_GRADE\020\004*f\n\017ETowerFloorType\022\032\n\026ETow"
    "er_Floor_TP_Battle\020\001\022\034\n\030ETower_Floor_TP_"
    "Question\020\002\022\031\n\025ETower_Floor_TP_Raids\020\003*\322\001"
    "\n\017EFloorLevelType\022\030\n\024EFloor_Level_TP_Non"
    "e\020\000\022\032\n\026EFloor_Level_TP_Battle\020\001\022\034\n\030EFloo"
    "r_Level_TP_Question\020\002\022\031\n\025EFloor_Level_TP"
    "_Opera\020\003\022\027\n\023EFloor_Level_TP_Box\020\004\022\031\n\025EFl"
    "oor_Level_TP_Raids\020\n\022\034\n\030EFloor_Level_TP_"
    "FIRST_IN\020\013", 1170);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cs_gamesystem.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cs_5fgamesystem_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cs_5fgamesystem_2eproto {
  StaticDescriptorInitializer_cs_5fgamesystem_2eproto() {
    protobuf_AddDesc_cs_5fgamesystem_2eproto();
  }
} static_descriptor_initializer_cs_5fgamesystem_2eproto_;
const ::google::protobuf::EnumDescriptor* EGameSystem_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EGameSystem_descriptor_;
}
bool EGameSystem_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 63:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ESystemModule_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ESystemModule_descriptor_;
}
bool ESystemModule_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ELevelMode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ELevelMode_descriptor_;
}
bool ELevelMode_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ESystemConditionType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ESystemConditionType_descriptor_;
}
bool ESystemConditionType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ETowerFloorType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ETowerFloorType_descriptor_;
}
bool ETowerFloorType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* EFloorLevelType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EFloorLevelType_descriptor_;
}
bool EFloorLevelType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SProtoSpace

// @@protoc_insertion_point(global_scope)
