// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_protoid.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cs_protoid.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SProtoSpace {

namespace {

const ::google::protobuf::EnumDescriptor* ECSProtoID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_cs_5fprotoid_2eproto() {
  protobuf_AddDesc_cs_5fprotoid_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cs_protoid.proto");
  GOOGLE_CHECK(file != NULL);
  ECSProtoID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cs_5fprotoid_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_cs_5fprotoid_2eproto() {
}

void protobuf_AddDesc_cs_5fprotoid_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020cs_protoid.proto\022\013SProtoSpace*\326\212\001\n\nECS"
    "ProtoID\022\034\n\027account_check_in_req_id\020\234\'\022\034\n"
    "\027account_check_in_ack_id\020\235\'\022\035\n\030account_r"
    "ole_data_ack_id\020\210\'\022\033\n\026create_role_of_gam"
    "e_id\020\211\'\022\037\n\032create_role_of_game_ack_id\020\212\'"
    "\022\030\n\023switch_scene_req_id\020\213\'\022\026\n\021enter_game"
    "_req_id\020\215\'\022\026\n\021enter_game_ack_id\020\221\'\022\026\n\021le"
    "ave_game_req_id\020\222\'\022\030\n\023gm_operation_req_i"
    "d\020\226\'\022\030\n\023gm_operation_ack_id\020\227\'\022\025\n\020kick_g"
    "ame_ntf_id\020\230\'\022\026\n\021beat_heart_ntf_id\020\231\'\022\025\n"
    "\020sync_time_ntf_id\020\232\'\022\026\n\021game_error_ntf_i"
    "d\020\233\'\022\035\n\030sys_packet_seq_id_req_id\020\236\'\022\035\n\030s"
    "ys_packet_seq_id_ack_id\020\237\'\022 \n\033sys_packet"
    "_seq_error_ntf_id\020\240\'\022\035\n\030sys_packet_seq_i"
    "d_ntf_id\020\241\'\022\035\n\030client_heart_beat_req_id\020"
    "\272\'\022\035\n\030client_heart_beat_ack_id\020\273\'\022\035\n\030cli"
    "ent_secret_key_req_id\020\304\'\022\035\n\030client_secre"
    "t_key_ack_id\020\305\'\022\037\n\032client_secret_start_r"
    "eq_id\020\306\'\022\037\n\032client_secret_start_ack_id\020\307"
    "\'\022!\n\034verify_config_version_req_id\020\316\'\022!\n\034"
    "verify_config_version_ack_id\020\317\'\022\033\n\026waiti"
    "ng_in_line_ntf_id\020\330\'\022\032\n\025finish_in_line_n"
    "tf_id\020\331\'\022\026\n\021role_guide_ntf_id\020\332\'\022\026\n\021role"
    "_guide_req_id\020\333\'\022\026\n\021role_guide_ack_id\020\334\'"
    "\022\035\n\030onekey_skip_guide_req_id\020\335\'\022\035\n\030oneke"
    "y_skip_guide_ack_id\020\336\'\022 \n\033exit_waiting_i"
    "n_line_req_id\020\337\'\022 \n\033exit_waiting_in_line"
    "_ack_id\020\340\'\022\034\n\027update_role_info_ntf_id\020\354\'"
    "\022\025\n\020role_info_ntf_id\020\356\'\022\034\n\027role_common_b"
    "ase_ntf_id\020\357\'\022\027\n\022item_packet_req_id\020\366\'\022\027"
    "\n\022item_packet_ack_id\020\367\'\022\024\n\017item_use_req_"
    "id\020\370\'\022\024\n\017item_use_ack_id\020\371\'\022\025\n\020item_sold"
    "_req_id\020\372\'\022\025\n\020item_sold_ack_id\020\373\'\022\026\n\021bag"
    "_expand_req_id\020\374\'\022\026\n\021bag_expand_ack_id\020\375"
    "\'\022#\n\036bag_capacity_not_enough_ntf_id\020\376\'\022\032"
    "\n\025get_role_chest_req_id\020\200(\022\032\n\025get_role_c"
    "hest_ack_id\020\201(\022\030\n\023update_chest_ntf_id\020\202("
    "\022\034\n\027role_player_info_ntf_id\020\320(\022#\n\036role_p"
    "layer_info_update_ntf_id\020\321(\022\036\n\031role_play"
    "er_change_req_id\020\322(\022\036\n\031role_player_chang"
    "e_ack_id\020\323(\022#\n\036role_player_active_skin_r"
    "eq_id\020\324(\022#\n\036role_player_active_skin_ack_"
    "id\020\325(\022 \n\033role_player_buy_skin_req_id\020\326(\022"
    " \n\033role_player_buy_skin_ack_id\020\327(\022!\n\034rol"
    "e_player_wear_skin_req_id\020\330(\022!\n\034role_pla"
    "yer_wear_skin_ack_id\020\331(\022\037\n\032role_player_s"
    "killup_ntf_id\020\332(\022\024\n\017role_buy_req_id\020\335(\022\024"
    "\n\017role_buy_ack_id\020\336(\022!\n\034role_show_player"
    "_base_req_id\020\337(\022!\n\034role_show_player_base"
    "_ack_id\020\340(\022\032\n\025role_show_like_req_id\020\341(\022\032"
    "\n\025role_show_like_ack_id\020\342(\022!\n\034role_show_"
    "change_name_req_id\020\343(\022!\n\034role_show_chang"
    "e_name_ack_id\020\344(\022%\n role_show_change_pos"
    "ition_req_id\020\345(\022%\n role_show_change_posi"
    "tion_ack_id\020\346(\022&\n!role_show_change_signa"
    "ture_req_id\020\347(\022&\n!role_show_change_signa"
    "ture_ack_id\020\350(\022\036\n\031role_show_set_hero_req"
    "_id\020\351(\022\036\n\031role_show_set_hero_ack_id\020\352(\022 "
    "\n\033role_show_set_border_req_id\020\353(\022 \n\033role"
    "_show_set_border_ack_id\020\354(\022\035\n\030role_show_"
    "comment_req_id\020\355(\022\035\n\030role_show_comment_a"
    "ck_id\020\356(\022$\n\037role_show_delete_comment_req"
    "_id\020\357(\022$\n\037role_show_delete_comment_ack_i"
    "d\020\360(\022!\n\034role_show_get_comment_req_id\020\361(\022"
    "!\n\034role_show_get_comment_ack_id\020\362(\022\037\n\032ro"
    "le_show_base_info_req_id\020\363(\022\037\n\032role_show"
    "_base_info_ack_id\020\364(\022\036\n\031role_show_get_li"
    "ke_req_id\020\366\001\022\036\n\031role_show_get_like_ack_i"
    "d\020\367\001\022 \n\033role_show_change_age_req_id\020\365(\022 "
    "\n\033role_show_change_age_ack_id\020\366(\022%\n role"
    "_show_change_starsign_req_id\020\367(\022%\n role_"
    "show_change_starsign_ack_id\020\370(\022%\n role_s"
    "how_change_birthday_req_id\020\371(\022%\n role_sh"
    "ow_change_birthday_ack_id\020\372(\022#\n\036role_sho"
    "w_change_labels_req_id\020\373(\022#\n\036role_show_c"
    "hange_labels_ack_id\020\374(\022!\n\034role_show_get_"
    "emotion_req_id\020\375(\022!\n\034role_show_get_emoti"
    "on_ack_id\020\376(\022#\n\036role_show_write_emotion_"
    "req_id\020\377(\022#\n\036role_show_write_emotion_ack"
    "_id\020\200)\022\"\n\035role_show_like_emotion_req_id\020"
    "\201)\022\"\n\035role_show_like_emotion_ack_id\020\202)\022%"
    "\n role_show_comment_emotion_req_id\020\203)\022%\n"
    " role_show_comment_emotion_ack_id\020\204)\022$\n\037"
    "role_show_remove_emotion_req_id\020\205)\022$\n\037ro"
    "le_show_remove_emotion_ack_id\020\206)\022$\n\037role"
    "_show_remove_comment_req_id\020\207)\022$\n\037role_s"
    "how_remove_comment_ack_id\020\210)\022\026\n\021soul_rai"
    "se_req_id\020\264)\022\026\n\021soul_raise_ack_id\020\265)\022\025\n\020"
    "soul_bind_req_id\020\266)\022\025\n\020soul_bind_ack_id\020"
    "\267)\022\027\n\022soul_unbind_req_id\020\270)\022\027\n\022soul_unbi"
    "nd_ack_id\020\271)\022\027\n\022soul_update_ntf_id\020\272)\022\025\n"
    "\020soul_lock_req_id\020\273)\022\025\n\020soul_lock_ack_id"
    "\020\274)\022\027\n\022soul_unlock_req_id\020\275)\022\027\n\022soul_unl"
    "ock_ack_id\020\276)\022\025\n\020soul_sell_req_id\020\277)\022\025\n\020"
    "soul_sell_ack_id\020\300)\022\032\n\025hero_list_data_nt"
    "f_id\020\230*\022\024\n\017add_hero_ntf_id\020\231*\022\027\n\022remove_"
    "hero_ntf_id\020\232*\022\030\n\023hero_upgrade_req_id\020\233*"
    "\022\030\n\023hero_upgrade_ack_id\020\234*\022\027\n\022hero_upsta"
    "r_req_id\020\235*\022\027\n\022hero_upstar_ack_id\020\236*\022\034\n\027"
    "hero_info_change_ntf_id\020\237*\022\027\n\022hero_awake"
    "n_req_id\020\240*\022\027\n\022hero_awaken_ack_id\020\241*\022\025\n\020"
    "hero_lock_req_id\020\242*\022\025\n\020hero_lock_ack_id\020"
    "\243*\022\030\n\023hero_compose_req_id\020\244*\022\030\n\023hero_com"
    "pose_ack_id\020\245*\022\034\n\027hero_skin_active_req_i"
    "d\020\246*\022\034\n\027hero_skin_active_ack_id\020\247*\022\037\n\032he"
    "ro_formation_data_ntf_id\020\250*\022\036\n\031hero_set_"
    "formation_req_id\020\251*\022\036\n\031hero_set_formatio"
    "n_ack_id\020\252*\022\034\n\027hero_change_name_req_id\020\253"
    "*\022\034\n\027hero_change_name_ack_id\020\254*\022\031\n\024hero_"
    "level_up_req_id\020\255*\022\031\n\024hero_level_up_ack_"
    "id\020\256*\022\030\n\023hero_star_up_req_id\020\257*\022\030\n\023hero_"
    "star_up_ack_id\020\260*\022\031\n\024hero_skill_up_req_i"
    "d\020\261*\022\031\n\024hero_skill_up_ack_id\020\262*\022-\n(role_"
    "battle_formation_fight_power_req_id\020\263*\022-"
    "\n(role_battle_formation_fight_power_ack_"
    "id\020\264*\022(\n#role_battle_hero_fight_power_re"
    "q_id\020\265*\022(\n#role_battle_hero_fight_power_"
    "ack_id\020\266*\022\026\n\021hero_equip_req_id\020\267*\022\026\n\021her"
    "o_equip_ack_id\020\270*\022\030\n\023hero_unequip_req_id"
    "\020\271*\022\030\n\023hero_unequip_ack_id\020\272*\022\037\n\032hero_eq"
    "uip_level_up_req_id\020\273*\022\037\n\032hero_equip_lev"
    "el_up_ack_id\020\274*\022&\n!hero_equip_onekey_lev"
    "el_up_req_id\020\275*\022&\n!hero_equip_onekey_lev"
    "el_up_ack_id\020\276*\022#\n\036hero_equip_all_level_"
    "up_req_id\020\277*\022#\n\036hero_equip_all_level_up_"
    "ack_id\020\300*\022\035\n\030hero_equip_onekey_req_id\020\301*"
    "\022\035\n\030hero_equip_onekey_ack_id\020\302*\022\037\n\032hero_"
    "unequip_onekey_req_id\020\303*\022\037\n\032hero_unequip"
    "_onekey_ack_id\020\304*\022\033\n\026hero_quality_up_req"
    "_id\020\305*\022\033\n\026hero_quality_up_ack_id\020\306*\022\030\n\023i"
    "tem_combine_req_id\020\307*\022\030\n\023item_combine_ac"
    "k_id\020\310*\022\030\n\023job_all_list_ntf_id\020\374*\022\026\n\021job"
    "_update_ntf_id\020\375*\022\031\n\024job_operation_req_i"
    "d\020\376*\022\031\n\024job_operation_ack_id\020\377*\022\026\n\021all_q"
    "uests_ntf_id\020\206+\022\031\n\024quests_update_ntf_id\020"
    "\207+\022\033\n\026get_quest_award_req_id\020\210+\022\033\n\026get_q"
    "uest_award_ack_id\020\211+\022%\n get_quest_activi"
    "ty_reward_req_id\020\212+\022%\n get_quest_activit"
    "y_reward_ack_id\020\213+\022\035\n\030shop_get_all_item_"
    "req_id\020\342+\022\035\n\030shop_get_all_item_ack_id\020\343+"
    "\022\031\n\024shop_buy_item_req_id\020\344+\022\031\n\024shop_buy_"
    "item_ack_id\020\345+\022\030\n\023shop_refresh_req_id\020\346+"
    "\022\030\n\023shop_refresh_ack_id\020\347+\022\025\n\020shop_open_"
    "ntf_id\020\350+\022\031\n\024shop_item_opt_req_id\020\351+\022\031\n\024"
    "shop_item_opt_ack_id\020\352+\022\030\n\023battle_ready_"
    "req_id\020\304,\022\030\n\023battle_ready_ack_id\020\305,\022\030\n\023b"
    "attle_ready_ntf_id\020\306,\022\036\n\031battle_change_h"
    "ero_req_id\020\307,\022\036\n\031battle_change_hero_ack_"
    "id\020\310,\022\036\n\031battle_change_hero_ntf_id\020\311,\022\037\n"
    "\032battle_shot_operate_req_id\020\312,\022\037\n\032battle"
    "_shot_operate_ack_id\020\313,\022\035\n\030battle_shot_b"
    "egin_ntf_id\020\314,\022\033\n\026battle_shot_end_ntf_id"
    "\020\315,\022\027\n\022battle_info_ntf_id\020\316,\022\030\n\023battle_b"
    "egin_ntf_id\020\317,\022\026\n\021battle_end_ntf_id\020\320,\022\026"
    "\n\021battle_1v1_req_id\020\321,\022\026\n\021battle_1v1_ack"
    "_id\020\322,\022\036\n\031battle_round_begin_ntf_id\020\323,\022\034"
    "\n\027battle_round_end_ntf_id\020\324,\022\035\n\030battle_t"
    "urn_begin_ntf_id\020\325,\022\033\n\026battle_turn_end_n"
    "tf_id\020\326,\022!\n\034battle_extra_operator_req_id"
    "\020\327,\022!\n\034battle_extra_operator_ack_id\020\330,\022!"
    "\n\034battle_extra_operator_ntf_id\020\331,\022\035\n\030bat"
    "tle_shot_ready_ntf_id\020\332,\022\034\n\027battle_jump_"
    "over_ntf_id\020\333,\022\030\n\023battle_begin_req_id\020\366,"
    "\022\030\n\023battle_begin_ack_id\020\367,\022\026\n\021battle_end"
    "_req_id\020\370,\022\026\n\021battle_end_ack_id\020\371,\022\036\n\031te"
    "st_office_battle_req_id\020\372,\022\036\n\031test_offic"
    "e_battle_ack_id\020\373,\022\031\n\024battle_replay_req_"
    "id\020\374,\022\031\n\024battle_replay_ack_id\020\375,\022\031\n\024disc"
    "over_info_ntf_id\020\250-\022\036\n\031discover_show_bos"
    "s_ntf_id\020\251-\022\032\n\025enter_discover_req_id\020\252-\022"
    "\032\n\025enter_discover_ack_id\020\253-\022\031\n\024exit_disc"
    "over_req_id\020\254-\022\031\n\024exit_discover_ack_id\020\255"
    "-\022\035\n\030discovery_mopping_req_id\020\256-\022\035\n\030disc"
    "overy_mopping_ack_id\020\257-\022\037\n\032discovery_buy"
    "_times_req_id\020\260-\022\037\n\032discovery_buy_times_"
    "ack_id\020\261-\022&\n!discovery_get_section_star_"
    "req_id\020\262-\022&\n!discovery_get_section_star_"
    "ack_id\020\263-\022\034\n\027role_plot_upload_req_id\020\274-\022"
    "\034\n\027role_plot_upload_ack_id\020\275-\022\031\n\024role_pl"
    "ot_get_req_id\020\276-\022\031\n\024role_plot_get_ack_id"
    "\020\277-\022\024\n\017plot_end_req_id\020\300-\022\024\n\017plot_end_ac"
    "k_id\020\301-\022\036\n\031plot_choose_branch_req_id\020\302-\022"
    "\036\n\031plot_choose_branch_ack_id\020\303-\022\034\n\027plot_"
    "chapter_end_req_id\020\304-\022\034\n\027plot_chapter_en"
    "d_ack_id\020\305-\022\037\n\032plot_trigger_action_req_i"
    "d\020\306-\022\037\n\032plot_trigger_action_ack_id\020\307-\022\037\n"
    "\032mail_set_one_status_req_id\020\310.\022\037\n\032mail_s"
    "et_one_status_ack_id\020\311.\022&\n!mail_set_mult"
    "i_mail_status_req_id\020\312.\022&\n!mail_set_mult"
    "i_mail_status_ack_id\020\313.\022\"\n\035mail_send_pri"
    "vate_mail_req_id\020\314.\022\"\n\035mail_send_private"
    "_mail_ack_id\020\315.\022\'\n\"mail_send_global_mail"
    "_debug_req_id\020\316.\022\'\n\"mail_send_global_mai"
    "l_debug_ack_id\020\317.\022&\n!mail_send_group_mai"
    "l_debug_req_id\020\320.\022&\n!mail_send_group_mai"
    "l_debug_ack_id\020\321.\022\'\n\"mail_send_family_ma"
    "il_debug_req_id\020\322.\022\'\n\"mail_send_family_m"
    "ail_debug_ack_id\020\323.\022\031\n\024mail_all_type_ntf"
    "_id\020\324.\022\035\n\030mail_del_all_type_req_id\020\325.\022\035\n"
    "\030mail_del_all_type_ack_id\020\326.\022\035\n\030mail_del"
    "_all_type_ntf_id\020\327.\022(\n#mail_send_private"
    "_mail_debug_req_id\020\330.\022(\n#mail_send_priva"
    "te_mail_debug_ack_id\020\331.\022\034\n\027del_cs_mul_ma"
    "ils_req_id\020\334.\022\034\n\027del_cs_mul_mails_ack_id"
    "\020\335.\022#\n\036sync_cs_mul_mails_state_req_id\020\336."
    "\022#\n\036sync_cs_mul_mails_state_ack_id\020\337.\022\033\n"
    "\026get_all_mail_cs_req_id\020\340.\022\033\n\026get_all_ma"
    "il_cs_ack_id\020\341.\022\033\n\026get_all_mail_cs_ntf_i"
    "d\020\342.\022\030\n\023send_mail_cs_req_id\020\343.\022\030\n\023send_m"
    "ail_cs_ack_id\020\344.\022\030\n\023del_cs_mails_ntf_id\020"
    "\345.\022\034\n\027chat_system_info_ntf_id\020\360.\022\026\n\021chat"
    "_world_req_id\020\361.\022\026\n\021chat_world_ntf_id\020\362."
    "\022\025\n\020chat_team_req_id\020\363.\022\025\n\020chat_team_ntf"
    "_id\020\364.\022\027\n\022chat_family_req_id\020\365.\022\027\n\022chat_"
    "family_ntf_id\020\366.\022\030\n\023chat_private_req_id\020"
    "\367.\022\030\n\023chat_private_ntf_id\020\370.\022%\n chat_wor"
    "ld_channel_change_req_id\020\371.\022%\n chat_worl"
    "d_channel_change_ack_id\020\372.\022%\n chat_world"
    "_channel_random_nft_id\020\373.\022#\n\036chat_broadc"
    "ast_all_area_req_id\020\374.\022#\n\036chat_broadcast"
    "_all_area_ack_id\020\375.\022#\n\036chat_broadcast_al"
    "l_area_ntf_id\020\376.\022\025\n\020chat_pack_ntf_id\020\377.\022"
    "\034\n\027marquee_all_type_ntf_id\020\204/\022\031\n\024marquee"
    "_debug_req_id\020\205/\022\026\n\021all_royals_ntf_id\020\324/"
    "\022\"\n\035royal_task_reward_draw_ntf_id\020\325/\022\"\n\035"
    "game_update_royal_task_req_id\020\326/\022\"\n\035game"
    "_update_royal_task_ack_id\020\327/\022\"\n\035game_roy"
    "al_draw_reward_req_id\020\330/\022\"\n\035game_royal_d"
    "raw_reward_ack_id\020\331/\022\037\n\032game_royal_all_d"
    "ata_req_id\020\332/\022\037\n\032game_royal_all_data_ack"
    "_id\020\333/\022#\n\036game_royal_refresh_data_req_id"
    "\020\334/\022#\n\036game_royal_refresh_data_ack_id\020\335/"
    "\022\"\n\035game_update_royal_task_ntf_id\020\336/\022\035\n\030"
    "game_royal_qingan_req_id\020\337/\022\035\n\030game_roya"
    "l_qingan_ack_id\020\340/\022\035\n\030game_royal_unlock_"
    "req_id\020\341/\022\035\n\030game_royal_unlock_ack_id\020\342/"
    "\022\034\n\027royal_pro_update_ntf_id\020\343/\022 \n\033game_b"
    "ranch_task_fin_req_id\020\344/\022 \n\033game_branch_"
    "task_fin_ack_id\020\345/\022&\n!game_royal_intimac"
    "y_reward_req_id\020\346/\022&\n!game_royal_intimac"
    "y_reward_ack_id\020\347/\022\033\n\026game_royal_chat_re"
    "q_id\020\350/\022\033\n\026game_royal_chat_ack_id\020\351/\022 \n\033"
    "game_royal_get_gifts_req_id\020\352/\022 \n\033game_r"
    "oyal_get_gifts_ack_id\020\353/\022 \n\033game_royal_g"
    "ive_gift_req_id\020\354/\022 \n\033game_royal_give_gi"
    "ft_ack_id\020\355/\022\033\n\026royal_base_info_ntf_id\020\356"
    "/\022\"\n\035game_royal_enter_scene_req_id\020\357/\022\"\n"
    "\035game_royal_enter_scene_ack_id\020\360/\022 \n\033gam"
    "e_royal_event_fin_req_id\020\361/\022 \n\033game_roya"
    "l_event_fin_ack_id\020\362/\022\032\n\025royal_all_info_"
    "req_id\020\363/\022\032\n\025royal_all_info_ack_id\020\364/\022\031\n"
    "\024royal_refresh_req_id\020\365/\022\031\n\024royal_refres"
    "h_ack_id\020\366/\022\027\n\022royal_visit_req_id\020\367/\022\027\n\022"
    "royal_visit_ack_id\020\370/\022\030\n\023royal_reward_nt"
    "f_id\020\371/\022%\n role_battle_formation_get_ntf"
    "_id\020\2700\022&\n!role_battle_formation_save_req"
    "_id\020\2720\022&\n!role_battle_formation_save_ack"
    "_id\020\2730\022\036\n\031game_search_friend_req_id\020\2341\022\036"
    "\n\031game_search_friend_ack_id\020\2351\022!\n\034friend"
    "_all_apply_info_ntf_id\020\2361\022\033\n\026game_add_fr"
    "iend_req_id\020\2371\022\033\n\026game_add_friend_ack_id"
    "\020\2401\022#\n\036game_process_apply_info_req_id\020\2411"
    "\022#\n\036game_process_apply_info_ack_id\020\2421\022\036\n"
    "\031game_add_blacklist_req_id\020\2431\022\036\n\031game_ad"
    "d_blacklist_ack_id\020\2441\022\036\n\031game_remove_fri"
    "end_req_id\020\2451\022\036\n\031game_remove_friend_ack_"
    "id\020\2461\022\032\n\025game_give_item_req_id\020\2471\022\032\n\025gam"
    "e_give_item_ack_id\020\2501\022%\n game_get_recomm"
    "end_friend_req_id\020\2511\022%\n game_get_recomme"
    "nd_friend_ack_id\020\2521\022\030\n\023game_friends_ntf_"
    "id\020\2531\022\033\n\026game_friend_opt_ntf_id\020\2541\022\032\n\025ga"
    "me_give_item_ntf_id\020\2551\022\"\n\035game_Onekey_ap"
    "ply_info_req_id\020\2561\022\"\n\035game_onekey_apply_"
    "info_ack_id\020\2571\022\037\n\032game_friend_refresh_re"
    "q_id\020\2601\022\037\n\032game_friend_refresh_ack_id\020\2611"
    "\022\036\n\031game_harem_compete_ntf_id\020\2002\022%\n game"
    "_harem_compete_qingan_req_id\020\2012\022%\n game_"
    "harem_compete_qingan_ack_id\020\2022\022#\n\036game_h"
    "arem_compete_slap_req_id\020\2032\022#\n\036game_hare"
    "m_compete_slap_ack_id\020\2042\022&\n!game_harem_c"
    "ompete_friends_req_id\020\2052\022&\n!game_harem_c"
    "ompete_friends_ack_id\020\2062\022#\n\036game_harem_c"
    "ompete_sync_ntf_id\020\2072\022$\n\037game_harem_comp"
    "ete_clear_req_id\020\2102\022$\n\037game_harem_compet"
    "e_clear_ack_id\020\2112\022%\n game_harem_compete_"
    "status_ntf_id\020\2122\022\'\n\"game_harem_compete_r"
    "edpoint_req_id\020\2132\022\'\n\"game_harem_compete_"
    "redpoint_ack_id\020\2142\022$\n\037game_harem_compete"
    "_share_req_id\020\2152\022$\n\037game_harem_compete_s"
    "hare_ack_id\020\2162\022(\n#game_harem_compete_get"
    "_event_req_id\020\2172\022(\n#game_harem_compete_g"
    "et_event_ack_id\020\2202\022&\n!game_harem_compete"
    "_tribute_req_id\020\2212\022&\n!game_harem_compete"
    "_tribute_ack_id\020\2222\022\027\n\022create_team_req_id"
    "\020\3442\022\027\n\022create_team_ack_id\020\3452\022\026\n\021enter_te"
    "am_req_id\020\3462\022\026\n\021enter_team_ack_id\020\3472\022\025\n\020"
    "exit_team_req_id\020\3502\022\025\n\020exit_team_ack_id\020"
    "\3512\022\027\n\022update_team_ntf_id\020\3522\022\026\n\021ready_tea"
    "m_req_id\020\3532\022\026\n\021ready_team_ack_id\020\3542\022\027\n\022u"
    "pdate_team_req_id\020\3552\022\027\n\022update_team_ack_"
    "id\020\3562\022\025\n\020get_teams_req_id\020\3572\022\025\n\020get_team"
    "s_ack_id\020\3602\022#\n\036invite_roles_enter_team_r"
    "eq_id\020\3612\022#\n\036invite_roles_enter_team_ack_"
    "id\020\3622\022\035\n\030invite_enter_team_ntf_id\020\3632\022\030\n\023"
    "offical_data_ntf_id\020\2554\022\034\n\027get_offical_ra"
    "nk_req_id\020\2564\022\034\n\027get_offical_rank_ack_id\020"
    "\2574\022\"\n\035challenge_offical_rank_req_id\020\2604\022\""
    "\n\035challenge_offical_rank_ack_id\020\2614\022\036\n\031ga"
    "me_officer_apply_req_id\020\2624\022\036\n\031game_offic"
    "er_apply_ack_id\020\2634\022\'\n\"offical_apply_batt"
    "le_result_req_id\020\2644\022\'\n\"offical_apply_bat"
    "tle_result_ack_id\020\2654\022 \n\033officer_daily_sa"
    "lary_req_id\020\2664\022 \n\033officer_daily_salary_a"
    "ck_id\020\2674\022\032\n\025officer_result_ntf_id\020\2704\022\034\n\027"
    "get_offical_data_req_id\020\2714\022\034\n\027get_offica"
    "l_data_ack_id\020\2724\022\"\n\035get_officer_applican"
    "ts_req_id\020\2734\022\"\n\035get_officer_applicants_a"
    "ck_id\020\2744\022 \n\033cancel_officer_apply_req_id\020"
    "\2754\022 \n\033cancel_officer_apply_ack_id\020\2764\022!\n\034"
    "share_officer_upgrade_req_id\020\2774\022!\n\034share"
    "_officer_upgrade_ack_id\020\3004\022%\n get_share_"
    "officer_upgrade_req_id\020\3014\022%\n get_share_o"
    "fficer_upgrade_ack_id\020\3024\022&\n!update_offic"
    "al_first_award_ntf_id\020\3034\022#\n\036get_offical_"
    "first_award_req_id\020\3044\022#\n\036get_offical_fir"
    "st_award_ack_id\020\3054\022\'\n\"get_offical_challe"
    "nge_roles_req_id\020\3064\022\'\n\"get_offical_chall"
    "enge_roles_ack_id\020\3074\022%\n add_offical_chal"
    "lenge_num_req_id\020\3104\022%\n add_offical_chall"
    "enge_num_ack_id\020\3114\022!\n\034offical_battle_rep"
    "ort_req_id\020\3124\022!\n\034offical_battle_report_a"
    "ck_id\020\3134\022!\n\034get_offical_rank_info_req_id"
    "\020\3144\022!\n\034get_offical_rank_info_ack_id\020\3154\022!"
    "\n\034get_offical_formation_req_id\020\3164\022!\n\034get"
    "_offical_formation_ack_id\020\3174\022\036\n\031get_offi"
    "cal_member_req_id\020\3204\022\036\n\031get_offical_memb"
    "er_ack_id\020\3214\022#\n\036get_global_offical_rank_"
    "req_id\020\3224\022#\n\036get_global_offical_rank_ack"
    "_id\020\3234\022\031\n\024get_rank_data_req_id\020\2215\022\031\n\024get"
    "_rank_data_ack_id\020\2225\022\035\n\030role_achievement"
    "s_ntf_id\020\3645\022(\n#role_achievement_get_rewa"
    "rds_req_id\020\3655\022(\n#role_achievement_get_re"
    "wards_ack_id\020\3665\022*\n%role_achievement_poin"
    "t_rewards_req_id\020\3675\022*\n%role_achievement_"
    "point_rewards_ack_id\020\3705\022\035\n\030event_msg_get"
    "_all_req_id\020\3306\022\035\n\030event_msg_get_all_ack_"
    "id\020\3316\022\032\n\025event_msg_read_req_id\020\3326\022\032\n\025eve"
    "nt_msg_read_ack_id\020\3336\022\031\n\024event_msg_del_r"
    "eq_id\020\3346\022\031\n\024event_msg_del_ack_id\020\3356\022\025\n\020e"
    "vent_msg_nty_id\020\3366\022\037\n\032event_msg_get_by_i"
    "d_req_id\020\3376\022\037\n\032event_msg_get_by_id_ack_i"
    "d\020\3406\022\033\n\026event_msg_by_id_nty_id\020\3416\022\026\n\021flo"
    "wer_bag_nty_id\020\2127\022\032\n\025flower_bag_all_req_"
    "id\020\2137\022\032\n\025flower_bag_all_ack_id\020\2147\022\027\n\022flo"
    "wer_send_req_id\020\2157\022\027\n\022flower_send_ack_id"
    "\020\2167\022\032\n\025flower_receive_nty_id\020\2177\022\032\n\025flowe"
    "r_bag_all_nty_id\020\2207\022\037\n\032role_draw_card_in"
    "fo_req_id\020\3476\022\037\n\032role_draw_card_info_ack_"
    "id\020\3506\022\032\n\025role_draw_card_req_id\020\3516\022\032\n\025rol"
    "e_draw_card_ack_id\020\3526\022\036\n\031role_draw_card_"
    "ssr_req_id\020\3536\022\036\n\031role_draw_card_ssr_ack_"
    "id\020\3546\022 \n\033role_talent_activate_req_id\020\2408\022"
    " \n\033role_talent_activate_ack_id\020\2418\022%\n all"
    "_role_talents_activate_req_id\020\2428\022%\n all_"
    "role_talents_activate_ack_id\020\2438\022\035\n\030switc"
    "h_role_skill_req_id\020\2448\022\035\n\030switch_role_sk"
    "ill_ack_id\020\2458\022\034\n\027role_fight_score_ntf_id"
    "\020\2468\022\027\n\022enter_tower_req_id\020\3238\022\027\n\022enter_to"
    "wer_ack_id\020\3248\022\036\n\031select_tower_floor_req_"
    "id\020\3258\022\036\n\031select_tower_floor_ack_id\020\3268\022\032\n"
    "\025question_check_req_id\020\3278\022\032\n\025question_ch"
    "eck_ack_id\020\3308\022\035\n\030update_tower_info_ntf_i"
    "d\020\3318\022\027\n\022tower_raids_req_id\020\3328\022\027\n\022tower_r"
    "aids_ack_id\020\3338\022\027\n\022tower_reset_req_id\020\3348\022"
    "\027\n\022tower_reset_ack_id\020\3358\022\030\n\023tower_reward"
    "_ntf_id\020\3368\022\037\n\032question_find_wrong_req_id"
    "\020\3378\022\037\n\032question_find_wrong_ack_id\020\3408\022\025\n\020"
    "tower_die_req_id\020\3418\022\025\n\020tower_die_ack_id\020"
    "\3428\022\033\n\026tower_step_fini_req_id\020\3438\022\033\n\026tower"
    "_step_fini_ack_id\020\3448\022\033\n\026enter_chat_room_"
    "req_id\020\2049\022\033\n\026enter_chat_room_ack_id\020\2059\022\032"
    "\n\025exit_chat_room_req_id\020\2069\022\032\n\025exit_chat_"
    "room_ack_id\020\2079\022$\n\037update_chat_room_playe"
    "rs_ntf_id\020\2109\022\034\n\027update_chat_view_ntf_id\020"
    "\2119\022\033\n\026report_position_req_id\020\2129\022\033\n\026repor"
    "t_position_ack_id\020\2139\022\035\n\030get_role_positio"
    "n_req_id\020\2149\022\035\n\030get_role_position_ack_id\020"
    "\2159\022\036\n\031get_chat_room_list_req_id\020\2169\022\036\n\031ge"
    "t_chat_room_list_ack_id\020\2179\022\020\n\013chat_req_i"
    "d\020\2209\022\020\n\013chat_ack_id\020\2219\022\036\n\031create_3dchat_"
    "room_req_id\020\2229\022\036\n\031create_3dchat_room_ack"
    "_id\020\2239\022!\n\034update_chat_room_data_ntf_id\020\224"
    "9\022\035\n\030get_hang_up_award_ntf_id\020\2259\022\034\n\027get_"
    "hang_up_info_ntf_id\020\2269\022$\n\037member_kick_3d"
    "_chat_room_req_id\020\2279\022$\n\037member_kick_3d_c"
    "hat_room_ack_id\020\2309\022 \n\033get_3d_chat_room_p"
    "os_req_id\020\2319\022 \n\033get_3d_chat_room_pos_ack"
    "_id\020\2329\022\034\n\027top_3d_chat_room_req_id\020\2339\022\034\n\027"
    "top_3d_chat_room_ack_id\020\2349\022$\n\037change_nam"
    "e_3d_chat_room_req_id\020\2359\022$\n\037change_name_"
    "3d_chat_room_ack_id\020\2369\022\030\n\023talisman_use_r"
    "eq_id\020\2669\022\030\n\023talisman_use_ack_id\020\2679\022\033\n\026ta"
    "lisman_un_use_req_id\020\2709\022\033\n\026talisman_un_u"
    "se_ack_id\020\2719\022\032\n\025talisman_lv_up_req_id\020\2729"
    "\022\032\n\025talisman_lv_up_ack_id\020\2739\022\032\n\025talisman"
    "_break_req_id\020\2749\022\032\n\025talisman_break_ack_i"
    "d\020\2759\022\033\n\026talisman_change_ntf_id\020\2769\022\022\n\rred"
    "_pt_req_id\020\3509\022\022\n\rred_pt_ack_id\020\3519\022\022\n\rred"
    "_pt_ntf_id\020\3529\022 \n\033get_wearing_fashions_re"
    "q_id\020\232:\022 \n\033get_wearing_fashions_ack_id\020\233"
    ":\022\034\n\027get_all_fashions_req_id\020\234:\022\034\n\027get_a"
    "ll_fashions_ack_id\020\235:\022%\n get_other_role_"
    "fashion_cs_req_id\020\237:\022%\n get_other_role_f"
    "ashion_cs_ack_id\020\240:\022\031\n\024wear_fashions_req"
    "_id\020\241:\022\031\n\024wear_fashions_ack_id\020\242:\022\025\n\020ent"
    "er_adv_req_id\020\314:\022\025\n\020enter_adv_ack_id\020\315:\022"
    "\033\n\026select_adv_city_req_id\020\316:\022\033\n\026select_a"
    "dv_city_ack_id\020\317:\022\025\n\020adv_event_req_id\020\320:"
    "\022\025\n\020adv_event_ack_id\020\321:\022\026\n\021adv_reward_nt"
    "f_id\020\322:\022\023\n\016adv_ask_req_id\020\323:\022\023\n\016adv_ask_"
    "ack_id\020\324:\022\026\n\021adv_tujian_req_id\020\325:\022\026\n\021adv"
    "_tujian_ack_id\020\326:\022\033\n\026adv_fixed_event_req"
    "_id\020\327:\022\033\n\026adv_fixed_event_ack_id\020\330:\022\025\n\020l"
    "eave_adv_req_id\020\331:\022\025\n\020leave_adv_ack_id\020\332"
    ":\022\031\n\024system_unlock_req_id\020\260;\022\031\n\024system_u"
    "nlock_ack_id\020\261;\022\031\n\024system_unlock_ntf_id\020"
    "\262;\022\033\n\026debug_hero_attr_ntf_id\020\224<\022\032\n\025barra"
    "ge_get_cs_req_id\020\370<\022\032\n\025barrage_get_cs_ac"
    "k_id\020\371<\022\033\n\026barrage_send_cs_req_id\020\372<\022\033\n\026"
    "barrage_send_cs_ack_id\020\373<\022\034\n\027user_event_"
    "track_ntf_id\020\214=\022 \n\033plot_little_game_set_"
    "req_id\020\252=\022 \n\033plot_little_game_set_ack_id"
    "\020\253=\022 \n\033plot_little_game_get_req_id\020\254=\022 \n"
    "\033plot_little_game_get_ack_id\020\255=\022\023\n\016pet_g"
    "et_req_id\020\264=\022\023\n\016pet_get_ack_id\020\265=\022\033\n\026pet"
    "_change_name_req_id\020\266=\022\033\n\026pet_change_nam"
    "e_ack_id\020\267=\022\031\n\024pet_do_action_req_id\020\270=\022\031"
    "\n\024pet_do_action_ack_id\020\271=\022\030\n\023pet_send_ou"
    "t_req_id\020\272=\022\030\n\023pet_send_out_ack_id\020\273=\022\035\n"
    "\030pet_get_out_award_req_id\020\274=\022\035\n\030pet_get_"
    "out_award_ack_id\020\275=\022\031\n\024pet_feed_food_req"
    "_id\020\276=\022\031\n\024pet_feed_food_ack_id\020\277=\022\034\n\027pet"
    "_set_show_pet_req_id\020\300=\022\034\n\027pet_set_show_"
    "pet_ack_id\020\301=\022\030\n\023pet_out_back_req_id\020\302=\022"
    "\030\n\023pet_out_back_ack_id\020\303=", 17785);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cs_protoid.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cs_5fprotoid_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cs_5fprotoid_2eproto {
  StaticDescriptorInitializer_cs_5fprotoid_2eproto() {
    protobuf_AddDesc_cs_5fprotoid_2eproto();
  }
} static_descriptor_initializer_cs_5fprotoid_2eproto_;
const ::google::protobuf::EnumDescriptor* ECSProtoID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ECSProtoID_descriptor_;
}
bool ECSProtoID_IsValid(int value) {
  switch(value) {
    case 246:
    case 247:
    case 5000:
    case 5001:
    case 5002:
    case 5003:
    case 5005:
    case 5009:
    case 5010:
    case 5014:
    case 5015:
    case 5016:
    case 5017:
    case 5018:
    case 5019:
    case 5020:
    case 5021:
    case 5022:
    case 5023:
    case 5024:
    case 5025:
    case 5050:
    case 5051:
    case 5060:
    case 5061:
    case 5062:
    case 5063:
    case 5070:
    case 5071:
    case 5080:
    case 5081:
    case 5082:
    case 5083:
    case 5084:
    case 5085:
    case 5086:
    case 5087:
    case 5088:
    case 5100:
    case 5102:
    case 5103:
    case 5110:
    case 5111:
    case 5112:
    case 5113:
    case 5114:
    case 5115:
    case 5116:
    case 5117:
    case 5118:
    case 5120:
    case 5121:
    case 5122:
    case 5200:
    case 5201:
    case 5202:
    case 5203:
    case 5204:
    case 5205:
    case 5206:
    case 5207:
    case 5208:
    case 5209:
    case 5210:
    case 5213:
    case 5214:
    case 5215:
    case 5216:
    case 5217:
    case 5218:
    case 5219:
    case 5220:
    case 5221:
    case 5222:
    case 5223:
    case 5224:
    case 5225:
    case 5226:
    case 5227:
    case 5228:
    case 5229:
    case 5230:
    case 5231:
    case 5232:
    case 5233:
    case 5234:
    case 5235:
    case 5236:
    case 5237:
    case 5238:
    case 5239:
    case 5240:
    case 5241:
    case 5242:
    case 5243:
    case 5244:
    case 5245:
    case 5246:
    case 5247:
    case 5248:
    case 5249:
    case 5250:
    case 5251:
    case 5252:
    case 5253:
    case 5254:
    case 5255:
    case 5256:
    case 5300:
    case 5301:
    case 5302:
    case 5303:
    case 5304:
    case 5305:
    case 5306:
    case 5307:
    case 5308:
    case 5309:
    case 5310:
    case 5311:
    case 5312:
    case 5400:
    case 5401:
    case 5402:
    case 5403:
    case 5404:
    case 5405:
    case 5406:
    case 5407:
    case 5408:
    case 5409:
    case 5410:
    case 5411:
    case 5412:
    case 5413:
    case 5414:
    case 5415:
    case 5416:
    case 5417:
    case 5418:
    case 5419:
    case 5420:
    case 5421:
    case 5422:
    case 5423:
    case 5424:
    case 5425:
    case 5426:
    case 5427:
    case 5428:
    case 5429:
    case 5430:
    case 5431:
    case 5432:
    case 5433:
    case 5434:
    case 5435:
    case 5436:
    case 5437:
    case 5438:
    case 5439:
    case 5440:
    case 5441:
    case 5442:
    case 5443:
    case 5444:
    case 5445:
    case 5446:
    case 5447:
    case 5448:
    case 5500:
    case 5501:
    case 5502:
    case 5503:
    case 5510:
    case 5511:
    case 5512:
    case 5513:
    case 5514:
    case 5515:
    case 5602:
    case 5603:
    case 5604:
    case 5605:
    case 5606:
    case 5607:
    case 5608:
    case 5609:
    case 5610:
    case 5700:
    case 5701:
    case 5702:
    case 5703:
    case 5704:
    case 5705:
    case 5706:
    case 5707:
    case 5708:
    case 5709:
    case 5710:
    case 5711:
    case 5712:
    case 5713:
    case 5714:
    case 5715:
    case 5716:
    case 5717:
    case 5718:
    case 5719:
    case 5720:
    case 5721:
    case 5722:
    case 5723:
    case 5750:
    case 5751:
    case 5752:
    case 5753:
    case 5754:
    case 5755:
    case 5756:
    case 5757:
    case 5800:
    case 5801:
    case 5802:
    case 5803:
    case 5804:
    case 5805:
    case 5806:
    case 5807:
    case 5808:
    case 5809:
    case 5810:
    case 5811:
    case 5820:
    case 5821:
    case 5822:
    case 5823:
    case 5824:
    case 5825:
    case 5826:
    case 5827:
    case 5828:
    case 5829:
    case 5830:
    case 5831:
    case 5960:
    case 5961:
    case 5962:
    case 5963:
    case 5964:
    case 5965:
    case 5966:
    case 5967:
    case 5968:
    case 5969:
    case 5970:
    case 5971:
    case 5972:
    case 5973:
    case 5974:
    case 5975:
    case 5976:
    case 5977:
    case 5980:
    case 5981:
    case 5982:
    case 5983:
    case 5984:
    case 5985:
    case 5986:
    case 5987:
    case 5988:
    case 5989:
    case 6000:
    case 6001:
    case 6002:
    case 6003:
    case 6004:
    case 6005:
    case 6006:
    case 6007:
    case 6008:
    case 6009:
    case 6010:
    case 6011:
    case 6012:
    case 6013:
    case 6014:
    case 6015:
    case 6020:
    case 6021:
    case 6100:
    case 6101:
    case 6102:
    case 6103:
    case 6104:
    case 6105:
    case 6106:
    case 6107:
    case 6108:
    case 6109:
    case 6110:
    case 6111:
    case 6112:
    case 6113:
    case 6114:
    case 6115:
    case 6116:
    case 6117:
    case 6118:
    case 6119:
    case 6120:
    case 6121:
    case 6122:
    case 6123:
    case 6124:
    case 6125:
    case 6126:
    case 6127:
    case 6128:
    case 6129:
    case 6130:
    case 6131:
    case 6132:
    case 6133:
    case 6134:
    case 6135:
    case 6136:
    case 6137:
    case 6200:
    case 6202:
    case 6203:
    case 6300:
    case 6301:
    case 6302:
    case 6303:
    case 6304:
    case 6305:
    case 6306:
    case 6307:
    case 6308:
    case 6309:
    case 6310:
    case 6311:
    case 6312:
    case 6313:
    case 6314:
    case 6315:
    case 6316:
    case 6317:
    case 6318:
    case 6319:
    case 6320:
    case 6321:
    case 6400:
    case 6401:
    case 6402:
    case 6403:
    case 6404:
    case 6405:
    case 6406:
    case 6407:
    case 6408:
    case 6409:
    case 6410:
    case 6411:
    case 6412:
    case 6413:
    case 6414:
    case 6415:
    case 6416:
    case 6417:
    case 6418:
    case 6500:
    case 6501:
    case 6502:
    case 6503:
    case 6504:
    case 6505:
    case 6506:
    case 6507:
    case 6508:
    case 6509:
    case 6510:
    case 6511:
    case 6512:
    case 6513:
    case 6514:
    case 6515:
    case 6701:
    case 6702:
    case 6703:
    case 6704:
    case 6705:
    case 6706:
    case 6707:
    case 6708:
    case 6709:
    case 6710:
    case 6711:
    case 6712:
    case 6713:
    case 6714:
    case 6715:
    case 6716:
    case 6717:
    case 6718:
    case 6719:
    case 6720:
    case 6721:
    case 6722:
    case 6723:
    case 6724:
    case 6725:
    case 6726:
    case 6727:
    case 6728:
    case 6729:
    case 6730:
    case 6731:
    case 6732:
    case 6733:
    case 6734:
    case 6735:
    case 6736:
    case 6737:
    case 6738:
    case 6739:
    case 6801:
    case 6802:
    case 6900:
    case 6901:
    case 6902:
    case 6903:
    case 6904:
    case 7000:
    case 7001:
    case 7002:
    case 7003:
    case 7004:
    case 7005:
    case 7006:
    case 7007:
    case 7008:
    case 7009:
    case 7015:
    case 7016:
    case 7017:
    case 7018:
    case 7019:
    case 7020:
    case 7050:
    case 7051:
    case 7052:
    case 7053:
    case 7054:
    case 7055:
    case 7056:
    case 7200:
    case 7201:
    case 7202:
    case 7203:
    case 7204:
    case 7205:
    case 7206:
    case 7251:
    case 7252:
    case 7253:
    case 7254:
    case 7255:
    case 7256:
    case 7257:
    case 7258:
    case 7259:
    case 7260:
    case 7261:
    case 7262:
    case 7263:
    case 7264:
    case 7265:
    case 7266:
    case 7267:
    case 7268:
    case 7300:
    case 7301:
    case 7302:
    case 7303:
    case 7304:
    case 7305:
    case 7306:
    case 7307:
    case 7308:
    case 7309:
    case 7310:
    case 7311:
    case 7312:
    case 7313:
    case 7314:
    case 7315:
    case 7316:
    case 7317:
    case 7318:
    case 7319:
    case 7320:
    case 7321:
    case 7322:
    case 7323:
    case 7324:
    case 7325:
    case 7326:
    case 7350:
    case 7351:
    case 7352:
    case 7353:
    case 7354:
    case 7355:
    case 7356:
    case 7357:
    case 7358:
    case 7400:
    case 7401:
    case 7402:
    case 7450:
    case 7451:
    case 7452:
    case 7453:
    case 7455:
    case 7456:
    case 7457:
    case 7458:
    case 7500:
    case 7501:
    case 7502:
    case 7503:
    case 7504:
    case 7505:
    case 7506:
    case 7507:
    case 7508:
    case 7509:
    case 7510:
    case 7511:
    case 7512:
    case 7513:
    case 7514:
    case 7600:
    case 7601:
    case 7602:
    case 7700:
    case 7800:
    case 7801:
    case 7802:
    case 7803:
    case 7820:
    case 7850:
    case 7851:
    case 7852:
    case 7853:
    case 7860:
    case 7861:
    case 7862:
    case 7863:
    case 7864:
    case 7865:
    case 7866:
    case 7867:
    case 7868:
    case 7869:
    case 7870:
    case 7871:
    case 7872:
    case 7873:
    case 7874:
    case 7875:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SProtoSpace

// @@protoc_insertion_point(global_scope)
