// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ss_protoid.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ss_protoid.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SProtoSpace {

namespace {

const ::google::protobuf::EnumDescriptor* ESSProtoID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_ss_5fprotoid_2eproto() {
  protobuf_AddDesc_ss_5fprotoid_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ss_protoid.proto");
  GOOGLE_CHECK(file != NULL);
  ESSProtoID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ss_5fprotoid_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_ss_5fprotoid_2eproto() {
}

void protobuf_AddDesc_ss_5fprotoid_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020ss_protoid.proto\022\013SProtoSpace*\252Y\n\nESSP"
    "rotoID\022\031\n\025gate_listen_report_id\020\001\022\033\n\027gat"
    "e_role_num_report_id\020\002\022\034\n\030role_login_ver"
    "ify_req_id\020\003\022\034\n\030role_login_verify_ack_id"
    "\020\004\022\023\n\017kick_out_req_id\020\005\022\023\n\017kick_out_ack_"
    "id\020\006\022\035\n\031gt_reconnect_check_req_id\020\007\022\035\n\031c"
    "t_reconnect_check_ack_id\020\010\022\034\n\030ct_reconne"
    "ct_kick_req_id\020\t\022\034\n\030gt_reconnect_kick_ac"
    "k_id\020\n\022\033\n\027gt_online_client_ntf_id\020\013\022$\n g"
    "t_game_server_player_num_ntf_id\020\014\022\031\n\025ct_"
    "need_queued_ntf_id\020\r\022\030\n\024ct_end_queued_nt"
    "f_id\020\016\022\032\n\026gt_queued_state_req_id\020\017\022\032\n\026ct"
    "_queued_state_ack_id\020\020\022\032\n\026gt_cancel_queu"
    "e_req_id\020\021\022\032\n\026ct_cancel_queue_ack_id\020\022\022\032"
    "\n\026role_leave_game_ntf_id\020\023\022\034\n\030account_lo"
    "gin_ntf_ack_id\020\036\022\030\n\024account_login_ntf_id"
    "\020\037\022\024\n\020area_list_req_id\020 \022\024\n\020area_list_ac"
    "k_id\020!\022\037\n\033area_gateserver_info_req_id\020\"\022"
    "\037\n\033area_gateserver_info_ack_id\020#\022\037\n\033area"
    "_gateserver_info_ntf_id\020$\022\027\n\023lc_heartbea"
    "t_req_id\020%\022\027\n\023lc_heartbeat_ack_id\020&\022\033\n\027u"
    "pdate_area_info_ntf_id\020(\022\032\n\026gm2center_cl"
    "ose_req_id\0203\022\032\n\026center2gm_close_ack_id\0204"
    "\022\"\n\036gm2center_center_status_req_id\0205\022\"\n\036"
    "center2gm_center_status_ack_id\0206\022!\n\035gm2c"
    "enter_center_reset_req_id\0207\022!\n\035center2gm"
    "_center_reset_ack_id\0208\022\031\n\025gm2l_heartbeat"
    "_req_id\020F\022\031\n\025l2gm_heartbeat_ack_id\020G\022\025\n\021"
    "gm2l_close_req_id\020H\022\037\n\033sync_connection_i"
    "nfo_req_id\020d\022\037\n\033sync_connection_info_ack"
    "_id\020e\022\034\n\030node_version_info_ntf_id\020f\022\036\n\032s"
    "ync_conection_info_ntf_id\020g\022\037\n\033register_"
    "listen_info_req_id\020h\022\034\n\030gm2manager_statu"
    "s_req_id\020n\022\034\n\030manager2gm_status_ack_id\020o"
    "\022\037\n\033gm2manager_area_info_req_id\020p\022\037\n\033man"
    "ager2gm_area_info_ack_id\020q\022\033\n\027gm_update_"
    "config_req_id\020r\022\033\n\027gm_update_config_ack_"
    "id\020s\022\033\n\027gm_update_config_ntf_id\020t\022\031\n\025con"
    "fig_version_req_id\020u\022\031\n\025config_version_a"
    "ck_id\020v\022\035\n\031area_update_config_req_id\020w\022\035"
    "\n\031area_update_config_ack_id\020x\022\035\n\031area_up"
    "date_config_ntf_id\020y\022\035\n\031area_cancel_upda"
    "te_req_id\020z\022\035\n\031area_cancel_update_ack_id"
    "\020{\022\"\n\036area_monitor_data_reset_ntf_id\020|\022\027"
    "\n\023gm_send_mail_req_id\020}\022\034\n\030gm_send_broad"
    "cast_req_id\020~\022\033\n\027gm_send_bulletin_req_id"
    "\020\177\022\034\n\027gm_send_shutdown_req_id\020\200\001\022\035\n\030assi"
    "gn_new_master_req_id\020\202\001\022 \n\033register_mast"
    "er_info_req_id\020\203\001\022#\n\036gm_open_login_white"
    "list_req_id\020\204\001\022\"\n\035gm_add_login_whitelist"
    "_req_id\020\205\001\022 \n\033db_account_role_data_req_i"
    "d\020\310\001\022 \n\033db_account_role_data_ack_id\020\311\001\022\036"
    "\n\031db_create_role_of_game_id\020\312\001\022\032\n\025db_cre"
    "ate_role_ack_id\020\313\001\022\031\n\024db_enter_game_req_"
    "id\020\314\001\022\031\n\024db_enter_game_ack_id\020\315\001\022\032\n\025game"
    "_role_info_req_id\020\316\001\022\032\n\025game_role_info_a"
    "ck_id\020\317\001\022\034\n\027gs_get_role_data_req_id\020\334\001\022\030"
    "\n\023db_role_data_ack_id\020\335\001\022\032\n\025gs_role_leav"
    "e_game_id\020\336\001\022\025\n\020save_role_req_id\020\337\001\022$\n\037d"
    "b_enter_game_check_role_req_id\020\340\001\022$\n\037gs_"
    "enter_game_check_role_ack_id\020\341\001\022\"\n\035db_ge"
    "t_redis_role_data_req_id\020\342\001\022\"\n\035db_get_re"
    "dis_role_data_ack_id\020\343\001\022%\n db_update_red"
    "is_role_data_ntf_id\020\344\001\022$\n\037db_role_show_g"
    "et_emotion_req_id\020\352\001\022$\n\037db_role_show_get"
    "_emotion_ack_id\020\353\001\022\035\n\030db_role_show_like_"
    "req_id\020\354\001\022\035\n\030db_role_show_like_ack_id\020\355\001"
    "\022 \n\033db_role_show_comment_req_id\020\356\001\022 \n\033db"
    "_role_show_comment_ack_id\020\357\001\022\'\n\"db_role_"
    "show_delete_comment_req_id\020\360\001\022\'\n\"db_role"
    "_show_delete_comment_ack_id\020\361\001\022$\n\037db_rol"
    "e_show_get_comment_req_id\020\362\001\022$\n\037db_role_"
    "show_get_comment_ack_id\020\363\001\022$\n\037db_role_sh"
    "ow_change_name_req_id\020\364\001\022$\n\037db_role_show"
    "_change_name_ack_id\020\365\001\022!\n\034db_role_show_g"
    "et_like_req_id\020\366\001\022!\n\034db_role_show_get_li"
    "ke_ack_id\020\367\001\022&\n!db_role_show_write_emoti"
    "on_req_id\020\370\001\022&\n!db_role_show_write_emoti"
    "on_ack_id\020\371\001\022%\n db_role_show_like_emotio"
    "n_req_id\020\372\001\022%\n db_role_show_like_emotion"
    "_ack_id\020\373\001\022(\n#db_role_show_comment_emoti"
    "on_ack_id\020\374\001\022(\n#db_role_show_comment_emo"
    "tion_req_id\020\375\001\022\'\n\"db_role_show_remove_em"
    "otion_req_id\020\376\001\022\'\n\"db_role_show_remove_e"
    "motion_ack_id\020\377\001\022\'\n\"db_role_show_remove_"
    "comment_req_id\020\200\002\022\'\n\"db_role_show_remove"
    "_comment_ack_id\020\201\002\022\037\n\032db_role_battle_inf"
    "o_req_id\020\204\002\022\037\n\032db_role_battle_info_ack_i"
    "d\020\205\002\022&\n!db_update_role_battle_info_ntf_i"
    "d\020\206\002\022\037\n\032db_check_apply_info_req_id\020\216\002\022\037\n"
    "\032db_check_apply_info_ack_id\020\217\002\022\036\n\031db_sav"
    "e_apply_info_req_id\020\220\002\022\033\n\026db_update_appl"
    "y_req_id\020\221\002\022!\n\034db_process_apply_info_req"
    "_id\020\222\002\022!\n\034db_process_apply_info_ack_id\020\223"
    "\002\022\034\n\027db_search_friend_req_id\020\224\002\022\034\n\027db_se"
    "arch_friend_ack_id\020\225\002\022\036\n\031db_save_friend_"
    "opt_req_id\020\226\002\022\037\n\032db_check_opt_record_req"
    "_id\020\227\002\022\037\n\032db_check_opt_record_ack_id\020\230\002\022"
    " \n\033db_update_opt_record_req_id\020\231\002\022#\n\036db_"
    "get_recommend_friend_req_id\020\232\002\022#\n\036db_get"
    "_recommend_friend_ack_id\020\233\002\022\"\n\035db_check_"
    "harem_compete_req_id\020\242\002\022\"\n\035db_check_hare"
    "m_compete_ack_id\020\243\002\022\"\n\035db_harem_compete_"
    "clear_req_id\020\244\002\022\036\n\031db_get_harem_event_re"
    "q_id\020\245\002\022\036\n\031db_get_harem_event_ack_id\020\246\002\022"
    "\036\n\031db_add_role_popularity_id\020\247\002\022)\n$mail_"
    "role_enter_game_get_mail_req_id\020\275\002\022)\n$ma"
    "il_role_enter_game_get_mail_ack_id\020\276\002\022+\n"
    "&mail_role_set_multi_mail_status_ntf_id\020"
    "\277\002\022$\n\037mail_role_del_multi_mail_ntf_id\020\300\002"
    "\022#\n\036mail_send_all_type_mail_req_id\020\301\002\022#\n"
    "\036mail_send_all_type_mail_ack_id\020\302\002\022$\n\037ma"
    "il_role_del_multi_mail_req_id\020\303\002\022$\n\037mail"
    "_role_del_multi_mail_ack_id\020\304\002\022&\n!mail_g"
    "et_game_all_role_ids_req_id\020\305\002\022&\n!mail_g"
    "et_game_all_role_ids_ack_id\020\306\002\022\036\n\031mail_o"
    "ne_role_mail_ntf_id\020\307\002\022 \n\033mail_multi_rol"
    "e_mail_ntf_id\020\310\002\022\035\n\030mail_svr_pressure_nt"
    "f_id\020\311\002\022\034\n\027del_ss_mul_mails_req_id\020\336\002\022\034\n"
    "\027del_ss_mul_mails_ack_id\020\337\002\022#\n\036sync_ss_m"
    "ul_mails_state_req_id\020\340\002\022#\n\036sync_ss_mul_"
    "mails_state_ack_id\020\341\002\022\030\n\023get_mails_ss_re"
    "q_id\020\342\002\022\030\n\023get_mails_ss_ack_id\020\343\002\022\030\n\023gen"
    "_mails_ss_req_id\020\344\002\022\030\n\023gen_mails_ss_ack_"
    "id\020\345\002\022\030\n\023send_mail_ss_req_id\020\346\002\022\030\n\023send_"
    "mail_ss_ack_id\020\347\002\022\030\n\023recv_mail_ss_ntf_id"
    "\020\350\002\022 \n\033mail_add_template_ss_req_id\020\351\002\022 \n"
    "\033mail_add_template_ss_ack_id\020\352\002\022 \n\033mail_"
    "add_template_ss_ntf_id\020\353\002\022 \n\033mail_new_te"
    "mplate_ss_ntf_id\020\354\002\022\032\n\025mail_red_pt_ss_re"
    "q_id\020\355\002\022\032\n\025mail_red_pt_ss_ack_id\020\356\002\022\034\n\027g"
    "s_create_battle_req_id\020\220\003\022\034\n\027gs_create_b"
    "attle_ack_id\020\221\003\022\034\n\027check_pve_result_req_"
    "id\020\222\003\022\034\n\027check_pve_result_ack_id\020\223\003\022#\n\036g"
    "s_create_office_battle_req_id\020\224\003\022#\n\036gs_c"
    "reate_office_battle_ack_id\020\225\003\022 \n\033gs_offi"
    "ce_battle_end_ntf_id\020\226\003\022\031\n\024cross_sign_in"
    "_req_id\020\364\003\022\031\n\024cross_sign_in_ack_id\020\365\003\022\025\n"
    "\020cross_ft_sync_id\020\366\003\022\024\n\017cross_ft_req_id\020"
    "\367\003\022\024\n\017cross_ft_ack_id\020\370\003\022\036\n\031role_enter_g"
    "ame_server_id\020\274\005\022\030\n\023gs_broadcast_req_id\020"
    "\275\005\022\032\n\025gs_change_name_req_id\020\276\005\022\032\n\025gt_cha"
    "nge_name_ret_id\020\277\005\022!\n\034gs_jump_to_cross_g"
    "ame_req_id\020\300\005\022\030\n\023gt_kick_role_ntf_id\020\301\005\022"
    "\031\n\024gs_player_num_ntf_id\020\302\005\022\037\n\032gate_forwa"
    "rd_search_req_id\020\303\005\022\036\n\031gate_search_frien"
    "d_ack_id\020\304\005\022\031\n\024gt_enter_game_ack_id\020\305\005\022\035"
    "\n\030chat_world_public_ntf_id\020\204\007\022\037\n\032chat_pr"
    "ivate_public_ntf_id\020\205\007\022\034\n\027chat_team_publ"
    "ic_ntf_id\020\206\007\022\036\n\031chat_family_public_ntf_i"
    "d\020\207\007\022!\n\034chat_broadcast_public_ntf_id\020\211\007\022"
    ",\n\'chat_world_change_channel_public_req_"
    "id\020\212\007\022,\n\'chat_world_change_channel_publi"
    "c_ack_id\020\213\007\022,\n\'chat_world_random_channel"
    "_public_req_id\020\214\007\022,\n\'chat_world_random_c"
    "hannel_public_ack_id\020\215\007\022\036\n\031chat_world_ch"
    "annel_ntf_id\020\216\007\022\032\n\025ps_create_team_req_id"
    "\020\350\007\022\032\n\025ps_create_team_ack_id\020\351\007\022\032\n\025ps_up"
    "date_team_ntf_id\020\352\007\022\031\n\024ps_enter_team_req"
    "_id\020\353\007\022\031\n\024ps_enter_team_ack_id\020\354\007\022\030\n\023ps_"
    "exit_team_req_id\020\355\007\022\030\n\023ps_exit_team_ack_"
    "id\020\356\007\022\031\n\024ps_ready_team_req_id\020\357\007\022\031\n\024ps_r"
    "eady_team_ack_id\020\360\007\022\032\n\025ps_update_team_re"
    "q_id\020\361\007\022\032\n\025ps_update_team_ack_id\020\362\007\022\030\n\023p"
    "s_get_teams_req_id\020\363\007\022\030\n\023ps_get_teams_ac"
    "k_id\020\364\007\022 \n\033ps_invite_enter_team_req_id\020\365"
    "\007\022 \n\033ps_invite_enter_team_ntf_id\020\366\007\022\037\n\032p"
    "s_get_offical_rank_req_id\020\314\010\022\037\n\032ps_get_o"
    "ffical_rank_ack_id\020\315\010\022)\n$ps_add_robot_to"
    "_offical_arena_req_id\020\316\010\022)\n$ps_add_robot"
    "_to_offical_arena_ack_id\020\317\010\022%\n ps_challe"
    "nge_offical_rank_req_id\020\320\010\022%\n ps_challen"
    "ge_offical_rank_ack_id\020\321\010\022&\n!ps_update_c"
    "hallenge_result_req_id\020\322\010\022&\n!ps_update_c"
    "hallenge_result_ack_id\020\323\010\022\"\n\035offical_exa"
    "mine_battle_req_id\020\324\010\022\"\n\035offical_examine"
    "_battle_ack_id\020\325\010\022*\n%ps_offical_apply_ba"
    "ttle_result_req_id\020\326\010\022*\n%ps_offical_appl"
    "y_battle_result_ack_id\020\327\010\022)\n$ps_test_off"
    "ical_battle_result_req_id\020\330\010\022(\n#ps_test_"
    "start_offical_battle_req_id\020\331\010\022#\n\036ps_tes"
    "t_offical_sign_up_req_id\020\332\010\022\036\n\031pub_offic"
    "er_result_ntf_id\020\333\010\022!\n\034pub_load_offical_"
    "data_req_id\020\334\010\022!\n\034pub_load_offical_data_"
    "ack_id\020\335\010\022&\n!pub_get_officer_applicants_"
    "req_id\020\336\010\022&\n!pub_get_officer_applicants_"
    "ack_id\020\337\010\022\036\n\031pub_offical_reduce_ntf_id\020\340"
    "\010\022%\n pub_offical_battle_report_req_id\020\341\010"
    "\022%\n pub_offical_battle_report_ack_id\020\342\010\022"
    " \n\033game_pub_msg_packing_ntf_id\020\260\t\022 \n\033pub"
    "_game_msg_packing_ntf_id\020\261\t\022&\n!game_pub_"
    "get_all_event_msg_ntf_id\020\342\t\022&\n!pub_game_"
    "get_all_event_msg_ntf_id\020\343\t\022%\n game_pub_"
    "delete_event_msg_ntf_id\020\344\t\022%\n game_pub_d"
    "elete_type_msgs_ntf_id\020\345\t\022#\n\036game_pub_re"
    "ad_event_msg_ntf_id\020\346\t\022%\n game_pub_inser"
    "t_event_msg_ntf_id\020\347\t\022%\n pub_game_insert"
    "_event_msg_ntf_id\020\350\t\022%\n game_pub_get_id_"
    "event_msg_ntf_id\020\351\t\022%\n pub_game_get_id_e"
    "vent_msg_ntf_id\020\352\t\022 \n\033game_pub_send_flow"
    "er_req_id\020\353\t\022 \n\033pub_game_send_flower_ack"
    "_id\020\354\t\022&\n!game_pub_flower_to_receive_nty"
    "_id\020\355\t\022&\n!pub_game_flower_to_receive_nty"
    "_id\020\356\t\022\034\n\027pub_role_login_batch_id\020\334\013\022\026\n\021"
    "pub_role_login_id\020\335\013\022\027\n\022pub_role_logout_"
    "id\020\336\013\022$\n\037pub_harem_compete_qingan_req_id"
    "\020\337\013\022\"\n\035pub_harem_compete_slap_req_id\020\340\013\022"
    "%\n pub_harem_compete_friends_req_id\020\341\013\022%"
    "\n pub_harem_compete_friends_ack_id\020\342\013\022\033\n"
    "\026pub_search_role_req_id\020\343\013\022\033\n\026pub_search"
    "_role_ack_id\020\344\013\022\035\n\030pub_officer_apply_req"
    "_id\020\345\013\022\035\n\030pub_officer_apply_ack_id\020\346\013\022\032\n"
    "\025pub_role_info_sync_id\020\347\013\022!\n\034pub_update_"
    "offical_lv_req_id\020\350\013\022$\n\037pub_cancel_offic"
    "al_apply_req_id\020\351\013\022$\n\037pub_cancel_offical"
    "_apply_ack_id\020\352\013\022\033\n\026pub_forward_add_req_"
    "id\020\353\013\022\033\n\026pub_forward_add_ack_id\020\354\013\022\"\n\035pu"
    "b_friend_opt_forward_req_id\020\355\013\022\"\n\035pub_fr"
    "iend_opt_forward_ack_id\020\356\013\022\030\n\023pub_get_ro"
    "le_req_id\020\357\013\022\030\n\023pub_get_role_ack_id\020\360\013\022\034"
    "\n\027pub_game_friends_ntf_id\020\361\013\022\035\n\030pub_comp"
    "lete_role_req_id\020\362\013\022\035\n\030pub_complete_role"
    "_ack_id\020\363\013\022\036\n\031pub_friend_refresh_req_id\020"
    "\364\013\022\036\n\031pub_friend_refresh_ack_id\020\365\013\022\"\n\035ga"
    "me_pub_get_rank_data_req_id\020\366\013\022\"\n\035game_p"
    "ub_get_rank_data_ack_id\020\367\013\022$\n\037db_share_o"
    "fficer_upgrade_req_id\020\370\013\022$\n\037db_share_off"
    "icer_upgrade_ack_id\020\371\013\022(\n#db_get_share_o"
    "fficer_upgrade_req_id\020\372\013\022(\n#db_get_share"
    "_officer_upgrade_ack_id\020\373\013\022\034\n\027update_ran"
    "k_data_ntf_id\020\374\013\022+\n&pub_get_offical_chal"
    "lenge_roles_req_id\020\375\013\022+\n&pub_get_offical"
    "_challenge_roles_ack_id\020\376\013\022\"\n\035update_her"
    "os_formation_ntf_id\020\377\013\022$\n\037pub_officer_da"
    "ily_salary_req_id\020\200\014\022$\n\037pub_officer_dail"
    "y_salary_ack_id\020\201\014\022$\n\037ps_get_offical_ran"
    "k_info_req_id\020\202\014\022$\n\037ps_get_offical_rank_"
    "info_ack_id\020\203\014\022%\n pub_get_offical_format"
    "ion_req_id\020\204\014\022%\n pub_get_offical_formati"
    "on_ack_id\020\205\014\022!\n\034pub_gm_upgrade_office_re"
    "q_id\020\206\014\022\035\n\030offical_robot_gen_req_id\020\207\014\022\035"
    "\n\030offical_robot_gen_ack_id\020\210\014\022 \n\033db_load"
    "_offical_data_req_id\020\211\014\022 \n\033db_load_offic"
    "al_data_ack_id\020\212\014\022 \n\033db_save_offical_dat"
    "a_req_id\020\213\014\022#\n\036pub_get_offical_members_r"
    "eq_id\020\214\014\022#\n\036pub_get_offical_members_ack_"
    "id\020\215\014\022\036\n\031pub_gm_start_match_req_id\020\216\014\022\036\n"
    "\031pub_gm_start_match_ack_id\020\217\014\022\"\n\035ps_glob"
    "al_offical_rank_req_id\020\220\014\022\"\n\035ps_global_o"
    "ffical_rank_ack_id\020\221\014\022#\n\036pub_gm_send_off"
    "ice_mail_req_id\020\222\014\022 \n\033pub_get_offical_da"
    "ta_req_id\020\223\014\022 \n\033pub_get_offical_data_ack"
    "_id\020\224\014\022\"\n\035pub_battle_replay_save_req_id\020"
    "\350\014\022\035\n\030pub_battle_replay_req_id\020\351\014\022\035\n\030pub"
    "_battle_replay_ack_id\020\352\014\022\033\n\026gs_create_sc"
    "ene_req_id\020\362\014\022\033\n\026gs_create_scene_ack_id\020"
    "\363\014\022\030\n\023gs_kick_role_req_id\020\364\014\022\030\n\023gs_kick_"
    "role_ack_id\020\365\014\022\033\n\026pub_query_scene_req_id"
    "\020\366\014\022\033\n\026pub_query_scene_ack_id\020\367\014\022!\n\034pub_"
    "scene_role_change_ntf_id\020\370\014\022\035\n\030pub_desto"
    "ry_scene_ntf_id\020\371\014\022\036\n\031allocate_chat_room"
    "_req_id\020\244\r\022\036\n\031allocate_chat_room_ack_id\020"
    "\245\r\022!\n\034get_minimum_chat_room_req_id\020\246\r\022!\n"
    "\034get_minimum_chat_room_ack_id\020\247\r\022\"\n\035pub_"
    "get_chat_room_list_req_id\020\250\r\022\"\n\035pub_get_"
    "chat_room_list_ack_id\020\251\r\022\036\n\031pub_get_role"
    "_gs_id_req_id\020\252\r\022\036\n\031pub_get_role_gs_id_a"
    "ck_id\020\253\r\022 \n\033gs_get_role_position_req_id\020"
    "\254\r\022 \n\033gs_get_role_position_ack_id\020\255\r\022\023\n\016"
    "gs_chat_req_id\020\256\r\022\023\n\016gs_chat_ack_id\020\257\r\022\030"
    "\n\023db_kick_role_req_id\020\260\r\022\030\n\023db_kick_role"
    "_ack_id\020\261\r\022\036\n\031pub_switch_game_id_ntf_id\020"
    "\262\r\022\"\n\035pub_create_3dchat_room_req_id\020\263\r\022\""
    "\n\035pub_create_3dchat_room_ack_id\020\264\r\022\037\n\032pu"
    "b_top_3dchat_room_req_id\020\265\r\022\037\n\032pub_top_3"
    "dchat_room_ack_id\020\266\r\022&\n!pub_cancel_top_3"
    "dchat_room_req_id\020\267\r\022&\n!pub_cancel_top_3"
    "dchat_room_ack_id\020\270\r\022$\n\037pub_update_3d_sc"
    "ene_info_ntf_id\020\271\r\022\'\n\"pub_change_name_3d"
    "chat_room_req_id\020\272\r\022\'\n\"pub_change_name_3"
    "dchat_room_ack_id\020\273\r\022\025\n\020red_pt_ss_ntf_id"
    "\020\211\016\022%\n get_other_role_fashion_ss_req_id\020"
    "\222\016\022%\n get_other_role_fashion_ss_ack_id\020\223"
    "\016\022\032\n\025barrage_get_ss_req_id\020\234\016\022\032\n\025barrage"
    "_get_ss_ack_id\020\235\016\022\033\n\026barrage_send_ss_req"
    "_id\020\236\016\022\033\n\026barrage_send_ss_ack_id\020\237\016\022\037\n\032u"
    "ser_event_track_ss_ntf_id\020\246\016", 11468);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ss_protoid.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ss_5fprotoid_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ss_5fprotoid_2eproto {
  StaticDescriptorInitializer_ss_5fprotoid_2eproto() {
    protobuf_AddDesc_ss_5fprotoid_2eproto();
  }
} static_descriptor_initializer_ss_5fprotoid_2eproto_;
const ::google::protobuf::EnumDescriptor* ESSProtoID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ESSProtoID_descriptor_;
}
bool ESSProtoID_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 40:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 70:
    case 71:
    case 72:
    case 100:
    case 101:
    case 102:
    case 103:
    case 104:
    case 110:
    case 111:
    case 112:
    case 113:
    case 114:
    case 115:
    case 116:
    case 117:
    case 118:
    case 119:
    case 120:
    case 121:
    case 122:
    case 123:
    case 124:
    case 125:
    case 126:
    case 127:
    case 128:
    case 130:
    case 131:
    case 132:
    case 133:
    case 200:
    case 201:
    case 202:
    case 203:
    case 204:
    case 205:
    case 206:
    case 207:
    case 220:
    case 221:
    case 222:
    case 223:
    case 224:
    case 225:
    case 226:
    case 227:
    case 228:
    case 234:
    case 235:
    case 236:
    case 237:
    case 238:
    case 239:
    case 240:
    case 241:
    case 242:
    case 243:
    case 244:
    case 245:
    case 246:
    case 247:
    case 248:
    case 249:
    case 250:
    case 251:
    case 252:
    case 253:
    case 254:
    case 255:
    case 256:
    case 257:
    case 260:
    case 261:
    case 262:
    case 270:
    case 271:
    case 272:
    case 273:
    case 274:
    case 275:
    case 276:
    case 277:
    case 278:
    case 279:
    case 280:
    case 281:
    case 282:
    case 283:
    case 290:
    case 291:
    case 292:
    case 293:
    case 294:
    case 295:
    case 317:
    case 318:
    case 319:
    case 320:
    case 321:
    case 322:
    case 323:
    case 324:
    case 325:
    case 326:
    case 327:
    case 328:
    case 329:
    case 350:
    case 351:
    case 352:
    case 353:
    case 354:
    case 355:
    case 356:
    case 357:
    case 358:
    case 359:
    case 360:
    case 361:
    case 362:
    case 363:
    case 364:
    case 365:
    case 366:
    case 400:
    case 401:
    case 402:
    case 403:
    case 404:
    case 405:
    case 406:
    case 500:
    case 501:
    case 502:
    case 503:
    case 504:
    case 700:
    case 701:
    case 702:
    case 703:
    case 704:
    case 705:
    case 706:
    case 707:
    case 708:
    case 709:
    case 900:
    case 901:
    case 902:
    case 903:
    case 905:
    case 906:
    case 907:
    case 908:
    case 909:
    case 910:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1009:
    case 1010:
    case 1011:
    case 1012:
    case 1013:
    case 1014:
    case 1100:
    case 1101:
    case 1102:
    case 1103:
    case 1104:
    case 1105:
    case 1106:
    case 1107:
    case 1108:
    case 1109:
    case 1110:
    case 1111:
    case 1112:
    case 1113:
    case 1114:
    case 1115:
    case 1116:
    case 1117:
    case 1118:
    case 1119:
    case 1120:
    case 1121:
    case 1122:
    case 1200:
    case 1201:
    case 1250:
    case 1251:
    case 1252:
    case 1253:
    case 1254:
    case 1255:
    case 1256:
    case 1257:
    case 1258:
    case 1259:
    case 1260:
    case 1261:
    case 1262:
    case 1500:
    case 1501:
    case 1502:
    case 1503:
    case 1504:
    case 1505:
    case 1506:
    case 1507:
    case 1508:
    case 1509:
    case 1510:
    case 1511:
    case 1512:
    case 1513:
    case 1514:
    case 1515:
    case 1516:
    case 1517:
    case 1518:
    case 1519:
    case 1520:
    case 1521:
    case 1522:
    case 1523:
    case 1524:
    case 1525:
    case 1526:
    case 1527:
    case 1528:
    case 1529:
    case 1530:
    case 1531:
    case 1532:
    case 1533:
    case 1534:
    case 1535:
    case 1536:
    case 1537:
    case 1538:
    case 1539:
    case 1540:
    case 1541:
    case 1542:
    case 1543:
    case 1544:
    case 1545:
    case 1546:
    case 1547:
    case 1548:
    case 1549:
    case 1550:
    case 1551:
    case 1552:
    case 1553:
    case 1554:
    case 1555:
    case 1556:
    case 1640:
    case 1641:
    case 1642:
    case 1650:
    case 1651:
    case 1652:
    case 1653:
    case 1654:
    case 1655:
    case 1656:
    case 1657:
    case 1700:
    case 1701:
    case 1702:
    case 1703:
    case 1704:
    case 1705:
    case 1706:
    case 1707:
    case 1708:
    case 1709:
    case 1710:
    case 1711:
    case 1712:
    case 1713:
    case 1714:
    case 1715:
    case 1716:
    case 1717:
    case 1718:
    case 1719:
    case 1720:
    case 1721:
    case 1722:
    case 1723:
    case 1801:
    case 1810:
    case 1811:
    case 1820:
    case 1821:
    case 1822:
    case 1823:
    case 1830:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SProtoSpace

// @@protoc_insertion_point(global_scope)
